### ISSUE TITLE
Support for jayson.client in browser context

### ISSUE THREAD

**Issue by CaulyKan** [tedeh/jayson#102]
Hello, I have a requirement to use jayson.client.http in browser, which by default will throw an exception about 'http' module. After examine the code I find out if I remove the Server reference the client runs perfectly. So would you consider making a client only version, or is there a feature that I missed?

Thank you!~

**Comment by tedeh** [comment]
Yes, I will look into it. Thanks for the feedback.

**Comment by tedeh** [comment]
Usage in the browser clarified in version v2.0.6. See https://github.com/tedeh/jayson/blob/master/README.md#clientbrowser

**Comment by aminmazi** [comment]
Hi, I didn't get how to use clientBrowser,
I need to send a JSON-RPC TCP request to an ip:50001, from a reactJS (browser) app.
the JSON RPC method is `server.version()`
would you please provide a sample code for this scenario?
