### ISSUE TITLE
Including jayson as an external dependency to an Angular/Typescript project

### ISSUE THREAD

**Issue by dcunited001** [tedeh/jayson#104]
Hey, I'm running into some issues with adding `jayson` as a type-naive javascript external dependency  to an Angular project. In particular, i'm getting a problem with [Line#22](https://github.com/tedeh/jayson/blob/master/lib/server/http.js#L22) in `http.js`:

```
require('util').inherits(HttpServer, http.Server);
```

It seems that my instance of `tsc` blows up at all mentions of `util.inherits`, a Node dependency. Do you know of any way to get around this? I can add some more code examples and console output to the issue when i get back to my laptop.

Also, I'm interested with the `index.d.ts` definitions file you're building in the `typescript` branch, but I can't quite get that branch to compile.

**Comment by tedeh** [comment]
Are you looking to use only the jayson client for your project?

You are right that the typescript branch probably does not compile — if you know typescript you are more than welcome to provide a contribution!

**Comment by tedeh** [comment]
There are now instructions for using jayson client side here: https://github.com/tedeh/jayson#clientbrowser
