### ISSUE TITLE
Add `options` parameter to `Client.prototype.request` method

### ISSUE THREAD

**Issue by sameoldmadness** [tedeh/jayson#106]
In my project I'm working with authentication method similar to HTTP Digest Authentication. The secret is unique per user, so I'd like to set the corresponding header on a per-request basis.

My first idea is to extend the `Client.prototype.request`.

```js
Client.prototype.request = function(method, params, id, headers = {}, callback);
```

Would it be ok if I provide a PR with this change? Or maybe there is a better way?

**Comment by tedeh** [comment]
Your best bet is to subclass Client and override the `_request` method if you want to insert funky logic that only has specific use-cases.

Look at the other client classes for examples.
