### ISSUE TITLE
Client support for communicating with servers expecting ndjson

### ISSUE THREAD

**Issue by pccasto** [tedeh/jayson#113]
Feature request, with pull offer.

I've finally figured out (after much wireshark viewing and head banging :-) ), the reason my jayson client would not get a response from the server I'm trying to use.  Seems the server expects the data to be in ndjson format (http://ndjson.org/) - basically adding newlines, or line-feed + newline after the last curly brace in the json packet.

I've patched my copy of jayson to accommodate, by providing an option when creating the client to set an append string value, defaulting to ''.  That value is then appended as part of the Utils.JSON.stringify function.

I could do this change up as a pull request if it is desired.  If so I'd get your preferred naming for the option, and your choice of where to expose the option. I think it is only needed in the client, or possibly only client.tcp, but am open to suggestions.  Would like to know that before going forward with changes to docs and tests. 

BR
~paul

**Comment by tedeh** [comment]
It is a bit tricky to say if this option should be included jayson - any interoperability between a jayson client or server with another JSON-RPC client or server is mostly accidental, since the particular issue you are referring to is not defined in any of the specs (should a tcp call be terminated with a line break).

I would need to think about this for a while...

**Comment by pccasto** [comment]
Certainly. 

I expected that you would need to think about the implications. I'm not sure why various server implementations require the line delimited JSON, but from a quick search, it appears that may be a few.  The one I'm working with is https://github.com/badaix/snapcast.

My current patch is getting me by the hurdle I needed to overcome. There is no rush for you to make a decision. I just wanted to offer it.  If you want to see what it looks like before deciding, I will let you know once I've forked/branched and applied this change.

BR
~paul

**Comment by pccasto** [comment]
Looks like @joelgallant put in a pull request related to this discussion a couple of days ago. His approach treats this as default, rather than optional. I'm not sure if that solves all use cases, since it is always appends just Unix line endings. I was going to leave it open to all the various options.

**Comment by tedeh** [comment]
I've decided to merge the pull request.

You can use it before I publish a new version by `npm install jayson@ 25eaeea50046ed0d8730737ebf9aacbe95882b1e `
