### ISSUE TITLE
Typescript definition issue: Server != server

### ISSUE THREAD

**Issue by jpike88** [tedeh/jayson#117]
![screen shot 2018-10-15 at 9 55 54 am](https://user-images.githubusercontent.com/9585787/46927657-bfe9ab80-d060-11e8-9c42-446fa9b84588.png)

I guess I'm adding a `new` is front of this? Documentation is not clear.

**Comment by tedeh** [comment]
Examples of how to use the typescript definitions in this purpose-built repository:

https://github.com/tedeh/jayson-typescript-test

I realise the definitions don't square with the examples in the README and main repository as it stands right now, however I'm a bit short of time right now.

Pull requests for the README or the type definition files are welcome.
