### ISSUE TITLE
Add helper method to auto detect http and https

### ISSUE THREAD

**Issue by gutenye** [tedeh/jayson#119]
Something like this

- jayson.client.httpAndHttps('http://localhost')
- jayson.client.httpAndHttps('https://localhost')

So that we don't need do this:

```
const api = url.parse(endpoint).protocol === 'http:' ? jayson.client.http(endpoint) : jayson.client.https(endpoint)
```

**Comment by tedeh** [comment]
I understand your issue, however I think this is best kept as a helper method in your own code. Jayson in this respect merely reflects how the internal node.js http and https modules work.
