### ISSUE TITLE
Add the ability to allow Jayson to support CORS requests.

### ISSUE THREAD

**Issue by rseward** [tedeh/jayson#12]
I have a short patch to lib/utils.js that enables Jayson to support CORS requests. 

It allows requestHeaders to be added to responses and supports requests with the HTTP OPTIONS methods.

I am a bit of a GITHUB newbie, so I am open to the best approach to submitting the patch if the project is open to receiving them.

With my changes CORS requests can be enabled by doing the following in server code:

```
var server = jayson.server({/* json rpc implementation*/});
var allowCors = {"Access-Control-Allow-Origin":"*", "Access-Control-Allow-Headers": "Origin, X-Requested-With, Content-Type, Accept"};

server.http( allowCors ).listen( 3000 );
```

Thank you,
Rob

**Comment by chrismbeckett** [comment]
Why is this issue closed? Does Jayson support CORS? It should :)

**Comment by tedeh** [comment]
I don't have the time to add this feature, but any pull requests are welcome.

**Comment by chrismbeckett** [comment]
With the support for Connect middleware, it should be possible to just use connect-cors, etc. So this probably is covered
