### ISSUE TITLE
Add async support to client

### ISSUE THREAD

**Issue by drortirosh** [tedeh/jayson#121]
the jayson/promise supports async/await, but its hard to use, since it returns response object, instead of just result.
e.g.
 Currently, you have to do:
```javascript
    res = await client.request( 'add', [2,3] )
    assert.equal( 2+3, res.result )
```
instead of using the result directly
```javascript
    assert.equal( 2+3, await client.request( 'add', [2,3] ) )
```
(any any error case should be thrown as an Error)

in order not to break an existing API, the above method can be renamed, e.g. to "call"

**Comment by tedeh** [comment]
```javascript
const { result, error } = await client.request( 'add', [2,3]);
```
