### ISSUE TITLE
Certificate error with https://jayson.tedeh.net

### ISSUE THREAD

**Issue by mceachen** [tedeh/jayson#122]
This server could not prove that it is jayson.tedeh.net; its security certificate is from salesboost.live. This may be caused by a misconfiguration or an attacker intercepting your connection.

https://www.ssllabs.com/ssltest/analyze.html?d=jayson.tedeh.net

**Comment by tedeh** [comment]
Thank you very much for the headsup, that is my domain so no attack is going on.

I must have misconfigured my webserver.
