### ISSUE TITLE
TypeScript type definitions missing for jayson/promise

### ISSUE THREAD

**Issue by Jannis** [tedeh/jayson#125]
When trying to use the Promise version of jayson in TypeScript, i.e.
```js
import * as jayson from 'jayson/promise'
```
the TypeScript compiler fails with:
```sh
TSError: Unable to compile TypeScript:
...: error TS7016: Could not find a declaration file for module 'jayson/promise'. ...
```

And indeed, while there are type definitions for the main library, there are none for `jayson/promise`.

**Comment by AlfieriChou** [comment]
@Jannis jayson@2.1.1 not index.d.ts in promise lib. @tedeh plz publish v2.1.2 to npm
