### ISSUE TITLE
Best practice to pass context to method functions

### ISSUE THREAD

**Issue by kityan** [tedeh/jayson#129]
Hello! Great job! Sorry for starting an issue, it's more like a quesion.
I'd like to pass come context object to my method functions. (e.g. user's authorization state, made with express before)
For now I use 'a dirty hack', simply inject additional object into req.body.params (or in each element of req.body array for batch requests). It looks ugly.

I belive that the only place to pass data from express request to server is here:
https://github.com/tedeh/jayson/blob/e8b231eb928b258567062e5602866f0739005023/lib/server/middleware.js#L34
But additional key here is agsaint JSON-RPC spec.

Also I can't do it event if I define a custom router, because I can't have there information from express request object...

What is you advice if any? Thanks a lot.

**Comment by tedeh** [comment]
Thank you for posting this.

A lot of people have been asking about this and work is in progress. Expect something this month!

**Comment by franck34** [comment]
+1

I'm using tcp/tls and need to pass a session context so i can play with it inside methods. I've redefined router so socket is passed as the last argument of all methods. JSON-RPC spec is broken, but it's work for now. See https://github.com/sloki-project/sloki/blob/master/src/transports/tcpJayson.js#L37 

@tedeh happy you work on it, thank you !

**Comment by tedeh** [comment]
Here is a preview version prepared for 3.0.0 release:

Link to the relevant README section:
https://github.com/tedeh/jayson/blob/v3_context/README.md#server-context

You can install directly from this branch like this: `npm install git://github.com/tedeh/jayson.git#v3_context`

I will just leave this here until early March, if no bugs or suggestions have crept up until then I will release it as 3.0.0.

**Comment by tedeh** [comment]
This feature has been released in 3.0.1 now.

**Comment by dimm0** [comment]
Is this: `if(err) return next(err);` right in the example? It returns an html for me in case of errors...

**Comment by HannesP** [comment]
@dimm0 this worked for me:
```js
res.send(result || err);
```

Since `err` is a JSON-RPC error, e.g. 
```js
{ jsonrpc: "2.0", id: 0, error: { code: 2000, message: "some error happened" } }
```
it makes sense to send it as the response.
