### ISSUE TITLE
TypeError: "rpc.discover" is a reserved method name

### ISSUE THREAD

**Issue by shanejonas** [tedeh/jayson#131]
I'm looking to implement a [service discovery method](https://github.com/open-rpc/spec#service-discovery-method) via [open-rpc](https://github.com/open-rpc/spec). And my server needs to implement `rpc.discover` as a system extension.

Any thoughts on adding `rpc.discover` as an allowed method name / system extension?

This somewhat relates to #100 and https://github.com/open-rpc/spec/issues/21#issuecomment-465821033

https://github.com/tedeh/jayson/blob/be1e188dc49b16bf06b374c062f073f38fb4b91d/lib/server/index.js#L134-L136

**Comment by tedeh** [comment]
Well, you can just manually add `rpc.discover` into `server._methods` just like `Server.prototype.method`does. I believe that is the best solution to your problem.

**Comment by BelfordZ** [comment]
@tedeh your suggestion is to use a method prefixed with underscore?

Im removing this Jayson lib from all of [OpenRPC](https://github.com/open-rpc) repos this week.

Thanks for the tip.

**Comment by BelfordZ** [comment]
https://github.com/open-rpc/mock-server/issues/73
https://github.com/open-rpc/generator-client/issues/123

**Comment by tedeh** [comment]
Here is a more concrete example on how you can add this method to a server, mainly meant for other people than Mr. Salty above.

```javascript
const jayson = require('jayson');
const server = new jayson.Server();

server._methods['rpc.discover'] = new jayson.Method(function(args, done) {
  // do stuff
});
```

**Comment by BelfordZ** [comment]
I prefix my public methods with `_` too!
