### ISSUE TITLE
Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by novo9** [tedeh/jayson#133]
I'm working on a new Vue.js project, after trying implement jayson into the project got the following error in my browser console:

**Firefox**:  _TypeError: superCtor is undefined;_
**Chrome**: _Uncaught TypeError: Cannot read property 'prototype' of undefined_ 

All the modules are up to date.

The problem occurs as soon as I importing the dependency in one of my components, like so: 

 `var jayson = require('jayson');`

My guesses about problem cause:
Despite jayson dependency is in direct dependencies list of package.json file, it still need to be imported directly in code by:

 `var jayson = require('jayson');
`

otherwise I get error: _"ReferenceError: jayson is not defined"_

package.json file 

```
  "dependencies": {
    "browser-sync": "^2.7.1",
    "jayson": "^2.1.2",
    "vue": "^2.6.6"
  },
```

**Comment by tedeh** [comment]
Please post the full stack trace of that error...

**Comment by novo9** [comment]
The compilation of the project goes well itself. I can see the error only in browser console. 

That's what the Chrome says:

```
Uncaught TypeError: Cannot read property 'prototype' of undefined
    at Object.inherits (inherits_browser.js?3fb5:5)
    at eval (http.js?7687:22)
    at Object../node_modules/jayson/lib/server/http.js (app.js:1933)
    at __webpack_require__ (app.js:724)
    at fn (app.js:101)
    at eval (index.js?0e79:80)
    at Object../node_modules/jayson/lib/server/index.js (app.js:1955)
    at __webpack_require__ (app.js:724)
    at fn (app.js:101)
    at eval (index.js?9c6c:17)
```

**Comment by novo9** [comment]
Everything turned out to be easier than I though:

Instead of using
`
var jayson = require('jayson');`

All I needed was:

`var jaysonBrowserClient = require('jayson/lib/client/browser');`

**Comment by kenfred** [comment]
This is still an problem. The issue happens any time you're trying to include the server code.
Like @novo9, I temporarily got around this by requiring only the client modules I need. However, when I tried to include the promise version of the tcp client, the problem cropped up again. That is because the promise tcp client does a `var jayson = require('../../../');`, which just pulls it all back in.

**Comment by kenfred** [comment]
I'm realizing this is because I'm in a client in a browser and not using the browser client. It must be that http is a core nodejs lib, and it is not available, as expected.

**Comment by tedeh** [comment]
https://github.com/tedeh/jayson#clientbrowser

**Comment by kaushik8888** [comment]
Unable to  make connection 
const rpc = url.parse('https://devgen:tKx2vJ5DTenuvduvsuovuvbvXhGSdC7XWj3DeaFBG6aPJ760ZA75UOtVUbDF8M@btctest8745912563.celticlab.com')

const jayson =require('jayson/lib/client/browser');
// const jaysonss = require('../../../node_modules/jayson');

const callServer = function(request, callback) {
  const options = {
    method: 'POST',
    body: request,
  };

  fetch(rpc,options)
    .then(function(res) { return res.text(); })
    .then(function(text) { callback(null, text); })
    .catch(function(err) { callback(err); });
};

// const client = jaysonBrowserClient(callServer);

const client = jayson(callServer)
