### ISSUE TITLE
Async batches

### ISSUE THREAD

**Issue by kityan** [tedeh/jayson#142]
Hello! Big thanks for your lib.
A little question. What do you think about changing this:
https://github.com/tedeh/jayson/blob/6bd3bcd03947b6765cfe7cd733233ff9dda6b293/lib/server/index.js#L425
to async (call with setTimeout/setImmediate). 
Of course, methods are async themselves, but they are called in sync loop. This may impact event loop in case of large request batches.

**Comment by tedeh** [comment]
Thanks.

I don't understand how it impacts the event loop, can you show me?

This example with a 100 000 promise batch works fine:

```javascript
'use strict';

const jayson = require('./master/promise');
const delay = require('delay');

const server = jayson.Server({
  doAsync: async args => {
    await delay(Math.round(Math.random() * 1000));
    return args.index;
  },
});

const client = jayson.Client(server);

const batch = [];
for(let index = 0; index < 100000; index++) {
  batch.push(client.request('doAsync', {index}, undefined, false));
}

client.request(batch).then(function(responses) {
  console.log(responses);
});
```

**Comment by kityan** [comment]
Hello! Sorry, I've missed this thread.
You are right. Using async functions for methods is OK.
