### ISSUE TITLE
Log invalid requests

### ISSUE THREAD

**Issue by mining-visualizer** [tedeh/jayson#146]
I have a public facing rpc server, and being concerned about security, I would like to log all invalid requests.  I need some ideas how to do that.  I tried the following, but it doesn't catch anything.  Any suggestions?

```javascript
rpcServer.on('http response', (res, req) => {
   if (res.statusCode != 200) {
      // log event to disk
      console.log('invalid rpc request');
   }
})
```

**Comment by tedeh** [comment]
See https://github.com/tedeh/jayson#what-is-the-recommended-way-to-use-jayson
