### ISSUE TITLE
Batch notifications [Async]

### ISSUE THREAD

**Issue by fjeddy** [tedeh/jayson#147]
Hello,

Amazing library, extremely simple and straight forward. Tho, I have hit a snag when using batch requests (Async).

It seems that the application is hanging on the batch request itself, and no code is executed after.

`batch[node].push( await nodes[node].request( 'setConfig', options, null, false ) )`
Adding all my requests to an array, using the false parameter due to async / await.

`await nodes[node].request( batch[node] )`
Actually sending the request, this code works, but will hang, the requests within the batch does not return anything, any of them, they are not meant to.

`await nodes[node].request( batch[node], [], null )`
This one gives me an error, saying `[object, Object],[object Object] must be a string`

Is it possible to send a batch request as a notification? Or is a response required?

**Comment by fjeddy** [comment]
Added proper responses to the request and did 

`batch[node].push( await nodes[node].request( 'setConfig', options, undefined, false ) )`

It no longer hangs and the code executes corretly in an orderly fashion. But it does give responses and is no longer handling the requests as notifications.

**Comment by tedeh** [comment]
Thanks, but is the server you are calling also using jayson? I can't replicate your error using a slightly amended example from [examples/promise_batches/client.js](https://github.com/tedeh/jayson/blob/master/examples/promise_batches/client.js):

```javascript
'use strict';

const jayson = require('../../promise');

const client = jayson.client.http({
  port: 3000
});

const batch = [
  client.request('add', [5, 6, 7, 8, 9], null, false),
  client.request('add', [1, 2, 3, 4, 5], undefined, false),
  client.request('add', [5, 6, 7, 8, 9], undefined, false),
];

client.request(batch).then(function(responses) {
  console.log(responses);
});
```

This works as expected, and returns two responses while calling the server method thrice.

**Comment by fjeddy** [comment]
My batch request does not consists of any responses, they are all notifications, hence no response at all. Perhaps thats where the issue lies?

I'm also using TCP, not HTTP, if it matters. I need to do some testing and debugging to give you a better response on when this happens, I've long forgotten about this :/

Will get back to you :)
