### ISSUE TITLE
unable to resolve http module in jayson/lib/client/http

### ISSUE THREAD

**Issue by shikhars371** [tedeh/jayson#148]
![1567683936043](https://user-images.githubusercontent.com/8435048/64339176-080b1700-d001-11e9-927a-1fb670c6231a.JPEG)
![Screenshot from 2019-09-05 17-18-24](https://user-images.githubusercontent.com/8435048/64339363-7b148d80-d001-11e9-9bff-f7e1642ed5d4.png)

**Comment by tedeh** [comment]
Sorry, but this issue is not actionable for me.

Also your error message says "Module 'http' does not exist in the Haste module map", I suggest you start looking that direction.

**Comment by shikhars371** [comment]
> Sorry, but this issue is not actionable for me.
> 
> Also your error message says "Module 'http' does not exist in the Haste module map", I suggest you start looking that direction.

are you kidding me , i have installed jayson and in it http exist
