### ISSUE TITLE
Twistlock flags test data as a compliance issue

### ISSUE THREAD

**Issue by davecrighton** [tedeh/jayson#156]
The IBM Product App Connect Enterprise has jayson as an indirect dependency. We have a customer who is scanning docker images created as part of their CI/CD pipeline with the Twistlock security tool.

This is flagging the test keys in the test/fixtures/keys directory as being secure credentials stored in the clear as described in the Embedded Secret Detection and Blocking section here:

https://www.twistlock.com/2017/04/17/introducing-twistlock-2-0/

We have informed our customer that we believe that removal of these files from the image will not adversely affect the function of the code and allow them to pass their security scans but wonder if the test data could be refactored to avoid the problem.

**Comment by tedeh** [comment]
Thanks, but these keys (https://github.com/tedeh/jayson/tree/master/test/fixtures/keys) were copied from the nodejs source repository many years ago to aid testing the TLS implementation and I would have to remove or disable these tests without them.

They might be "secure keys" but not in any practical sense since they are only used for tests.

Nodejs source still contains keys like this: https://github.com/nodejs/node/tree/master/test/fixtures/keys

**Comment by davecrighton** [comment]
Hi @tedeh 

Thanks for the fast response. 

I do realise that this is a false positive from the scanner but out of the nearly 1200 node modules in our dependency tree only 4 have this issue (I have also raised similar issue on those repos) so I feel like there might be a common solution to this (sorry I'm primarily a C++/Java dev so not totally familiar with current node.js best practices)

Although the test keys are in the source tree for node.js they are not actually distributed so don't trigger the scanner. 

Is there any easy way to make the keys a dev or build time dependency?

If it really is impractical and I get a similar response from the other repos then I will also try engaging Twistlock to see if they have a process for excluding well known test data.

Thanks again for taking the time to respond, it really is very much appreciate.

**Comment by tedeh** [comment]
I've ignored the test files now with npmignore now, you can checkout `v3.2.0` which is published without.

**Comment by davecrighton** [comment]
That's great, thanks a lot for your help on this one.
