### ISSUE TITLE
websocket server and client implementation

### ISSUE THREAD

**Issue by aalex** [tedeh/jayson#158]
It would be useful to also have a websocket server and client implementation, so that we can create bi-directional communication between the client and the server. That would allow the server to send low-latency notifications to the client, anytime.

**Comment by tedeh** [comment]
I agree, and believe it or not I am working on it.

**Comment by tedeh** [comment]
This just landed in 85c5b48 – uncodumented so far but I invite people to give feedback here before I deploy it.

**Comment by tedeh** [comment]
This got published a little bit unexpectedly in `v3.6.4` but you will have to look in the master README for documentation and examples.
