### ISSUE TITLE
Prevent port from being set as 80

### ISSUE THREAD

**Issue by saharsa** [tedeh/jayson#159]
Hi. 

I am trying to invoke the 'generateInteger' method of https://api.random.org/json-rpc/2/invoke.

![image](https://user-images.githubusercontent.com/15059737/71232251-36460580-2317-11ea-8ec5-b433641fc1f9.png)

![image](https://user-images.githubusercontent.com/15059737/71232273-507fe380-2317-11ea-9a87-f2f7942c1bf3.png)

Is there any way I can prevent the port from being set as 80 when the request is being made?

**Comment by tedeh** [comment]
Use `jayson.Client.https`

**Comment by saharsa** [comment]
Now it is setting the port as 443.

**Comment by saharsa** [comment]
> Use `jayson.Client.https`

Now it is setting the port as 443.
