### ISSUE TITLE
Utils.request docs missing

### ISSUE THREAD

**Issue by nombrekeff** [tedeh/jayson#161]
hey there, it seems that `jayson.Utils.request` is missing in the docs, although it is available in the library. Is this intentional?  I would like to be able to reference it in the docs!

It's missing here: https://jayson.tedeh.net/3.2.0/Utils.html

I'm using `jayson@3.2.0`

**Comment by tedeh** [comment]
Thanks. This is fixed now, but only for the latest version of the docs: https://jayson.tedeh.net/3.2.0/Utils.html

**Comment by nombrekeff** [comment]
Nice! Thank you!
