### ISSUE TITLE
Validate data before sending it back to client

### ISSUE THREAD

**Issue by mitjafelicijan** [tedeh/jayson#162]
Hi, I am implementing JSON schema validation for response result messages and was wondering how would I intercept the body before being sent back to the client to do some validation of data.

I have tried replacer but that only works on a single key.

I have also tried middleware with express but I was unable to do it even with `express-mung`. Worked on normal routes but not RPC ones.

I don't intend to use express if not necessary.

**Q: How do I intercept response from getting sent to the client to do some validation without having this logic inside actual RPC methods?**

Thanks in advance

**Comment by tedeh** [comment]
I think understand what you mean.

You could use express but since you don't want to your best bet is to wrap your server methods which is very easy and middleware-like anyway. I have added an example here: https://github.com/tedeh/jayson/tree/master/examples/method_wrapping
