### ISSUE TITLE
TypeScript definition for the browser interface is missing

### ISSUE THREAD

**Issue by amphineko** [tedeh/jayson#164]
https://github.com/tedeh/jayson/blob/8db9c541624948f9ec12bff21568b62589ead5d1/index.d.ts#L260

It seems like `index.d.ts` doesn't cover the `Client.browser` interface.  
The `Client` interface defined here doesn't contain a `browser` property.

![image](https://user-images.githubusercontent.com/2821430/83297445-28c96b80-a225-11ea-9122-114f0c51a26a.png)

And importing `jayson/lib/client/browser` gives an error.  
I'm creating a project-local d.ts as a workaround.

**Comment by tedeh** [comment]
Please share your project-local workaround in a pull request as a benefit to everyone else...

**Comment by tedeh** [comment]
I have added a type declaration in version `v3.3.2`.
