### ISSUE TITLE
Multiple relays

### ISSUE THREAD

**Issue by fjeddy** [tedeh/jayson#165]
Hello,

How would I go about if I wanted an event to relay to not just one client, but multiple clients.

Instead of

```
const server = jayson.server({
  add: jayson.client.http({
    port: 3001
  })
});
```

Then I would want to do something along the lines off

```
const server = jayson.server({
  add: [
    jayson.client.http({
      port: 3001
    }),
    jayson.client.http({
      port: 3002
    })
  ]
});
```

Is it possible?

**Comment by tedeh** [comment]
Just create a method handler that itself passes jayson calls to other apis.
