### ISSUE TITLE
Default method handler

### ISSUE THREAD

**Issue by bitwiseguy** [tedeh/jayson#170]
Is there a way to define a default method handler? I am creating a jsonrpc relay server which handles some methods and relays the rest. Instead of individually specifying the name for each method to relay, can I just say "relay any method not defined in this server"? Is something similar to the following possible?

```javascript
export const rpcServer = new jayson.Server(
  {
    method_1: method_1_definition,
    method_2: method_2_definition,
    default: relayRequest_definition
  },
  {
    useContext: true,
  },
);
```

**Comment by tedeh** [comment]
https://github.com/tedeh/jayson#method-routing
