### ISSUE TITLE
BadRequestError: request aborted

### ISSUE THREAD

**Issue by turboboost55** [tedeh/jayson#172]
I recently modified my Jayson RPC server so it could pick up the clients IP address.  I used the sample code you have under your FAQ "What is the recommended way to use jayson?" almost exactly as is.  Ever since then I am seeing intermittent errors as follows:

```
BadRequestError: request aborted
    at IncomingMessage.onAborted (/home/user/myproject/node_modules/raw-body/index.js:231:10)
    at IncomingMessage.emit (events.js:198:13)
    at abortIncoming (_http_server.js:462:9)
    at socketOnClose (_http_server.js:455:3)
    at Socket.emit (events.js:203:15)
    at TCP._handle.close (net.js:607:12)
```
It doesn't seem to be having any significant impact on my server, and I haven't heard any reports from the clients that are connecting to my server, but it is rather annoying as I've got an alert system set up that triggers whenever something shows up on `console.error`.

I know it probably has nothing to do with your code, but I was wondering  if you have seen this before, or if you have any suggestions?

**Comment by tedeh** [comment]
Sorry but I don't know why your connection breaks. Stack doesn't even include jayson. Maybe timeouts...

**Comment by turboboost55** [comment]
Timeouts are a definite possibility.  I was just looking for some ideas/suggestions as to how I can trap or handle that error (so I can ignore it), rather than have it puke a message on my error console.
