### ISSUE TITLE
data size limit on client requests

### ISSUE THREAD

**Issue by bendxr** [tedeh/jayson#175]
Hi, 

I'm using Jayson in its simple use case, but I've data limit issue on client requests. 
Some parameter could be big (8.5 MB in my case) and I've found that the data passed into the method callback are lacking of several hundred of KB.
May it be a limit set inside Jayson lib ?
May it be solved by setting an express context like [described here](https://github.com/tedeh/jayson/blob/master/examples/faq_recommended_http_server/server.js) and therefore setting something like :  
`app.use(bodyParser.json({ limit: '50mb' }));` ?

Best regards,

**Comment by tedeh** [comment]
Yes, you can absolutely try that and see if it works.

**Comment by bendxr** [comment]
For info and to complete the question asked in the issue : there was no limit (in any case, not at such a low limit) in server-side Jayson code. The real issue was in the client's faulty JSON parsing code which discarded data.

Best regards,
