### ISSUE TITLE
TCP client timeout support

### ISSUE THREAD

**Issue by pluswave** [tedeh/jayson#176]
currently, doesn't support tcp client timeout. I want this feature.

**Comment by tedeh** [comment]
https://github.com/tedeh/jayson#what-is-the-recommended-way-to-use-jayson

**Comment by pluswave** [comment]
Why close this issue? I mean , a **TCP** client  (not http ). 
````
jayson.client.tcp()
````
for now, I just use a PromiseTimeout ( from a stackoverflow answer ) for workaround

````
const promiseTimeout = function(ms, promise){

  // Create a promise that rejects in <ms> milliseconds
  let timeout = new Promise((resolve, reject) => {
    let id = setTimeout(() => {
      clearTimeout(id);
      reject('Timed out in '+ ms + 'ms.')
    }, ms)
  })

  // Returns a race between our timeout and the passed in promise
  return Promise.race([
    promise,
    timeout
  ])
}

````

**Comment by tedeh** [comment]
Beginning with version `jayson@3.5.2` you can now get the TCP or TLS socket object via an event described here: https://github.com/tedeh/jayson#clienttcp-events

This should allow you to setup custom handling for TCP timeouts without the library having to add too many opinions on how they should work.
