### ISSUE TITLE
gzip compression + alternate headers for server middleware

### ISSUE THREAD

**Issue by jpike88** [tedeh/jayson#177]
As we know, gzip compression is extremely effective for minimising payload size. But when it is enabled, modern browsers do not allow XMLHTTPRequest calls to measure download progress on the response.

_More information:_

_The 'content-length' header is omitted one the response, as gzip content is assumed to be returned in a chunked stream. Obviously for things like jayson, this is not the case. But this still means that download progress cannot be determined by the client._

_To get around this, a polyfill exists which can look for a custom HTTP header (default 'x-decompressed-content-length'): https://github.com/AirConsole/xmlhttprequest-length-computable_

I think devs that use Jayson could benefit from a very simple optional gzip implementation, that also sets an alternate header which allows devs to implement download progress monitoring for compressed responses. It's also 'cleaner' and less error prone if it sits within the error-checks in the middleware function (i.e. isMethod).

My implementation below, using the 'zlib' library

```
(req, res: ServerResponse, next) => {
		privateJaysonServer.call(req.body, context, (err, methodResult) => {
			if (err) {
				return next(err);
			}
			try {
				const bufferedData = Buffer.from(JSON.stringify(methodResult || {}));
				zlib.gzip(bufferedData, (_, result) => {
					// The callback will give you the
					res.setHeader('Content-Length', Buffer.byteLength(result));
					res.setHeader('Content-Encoding', 'gzip');
					res.setHeader(
						'x-decompressed-content-length',
						Buffer.byteLength(bufferedData)
					);
					res.end(result); // result, so just send it.
				});
			} catch (error) {
				core.reportError(error);
			}
		});
	},
```

@tedeh thoughts?

**Comment by tedeh** [comment]
Gzip is really good but this is solved with middleware, it should not be part of jayson core.

To expand on the [README examples under "Recommended usage"](https://github.com/tedeh/jayson#what-is-the-recommended-way-to-use-jayson), with new comments relating to this issue:

```javascript
'use strict';

const _ = require('lodash');
const jayson = require('./../..');
const jsonParser = require('body-parser').json;
const express = require('express');
const compression = require('compression'); // express gzip middleware
const app = express();

const server = jayson.server({
  add: function(numbers, callback) {
    callback(null, _.reduce(numbers, (sum, val) => sum + val, 0));
  }
});

app.use(compression());  // all responses are now gzip compressed
app.use(jsonParser()); // body-parser automatically inflates gzip already
app.use(function(req, res, next) {
  const request = req.body;
  server.call(request, function(err, response) {
    if(err) {
      if(err instanceof Error) return next(err);
      res.status(400);
      res.send(err);
      return;
    }
    if(response) {
      res.send(response);
    } else {
      res.status(204);
      res.send('');
    }
  });
});

app.listen(3001);
```
