### ISSUE TITLE
Compliant JSON-RPC 2.0 client notifications

### ISSUE THREAD

**Issue by dudecc** [tedeh/jayson#179]
Unlike JSON-RPC 1.0, JSON-RPC 2.0 requires that the id field not be present at all in a notification.  The recommended way to produce a notification from a jayson Client is to pass in an id of null, which currently results in an output packet with an id field set to null regardless of whether JSON-RPC 1.0 or JSON-RPC 2.0 is selected.  As such there does not appear to be any way to generate valid JSON-RPC 2.0 notifications using a jayson Client.

**Comment by tedeh** [comment]
I agree that there should be a way to generate 2.0 notifications with the id field not present, however I will note that the 2.0 specification does not *require* the "id" field to not be present at all. The phrases used are "discouraged" and "SHOULD normally not be null". So you are incorrect to say that jayson does not generate valid JSON-RPC 2.0 notifications presently.

Now I will think of a way to add this capability to the "request generator" function that that may or may not warrant a major version increase, and then return to close this issue with a reference to the updated version.

Thanks for bringing this to my attention.
