### ISSUE TITLE
Server.call type definitions and docs outdated

### ISSUE THREAD

**Issue by ctusch** [tedeh/jayson#181]
From reading the sources it seems like `Server.call`'s `originalCallback` always gets passed a complete JSON RPC response object, either as its first or as its second parameter (or non at all).

The type definition defines the first parameter as
```js
type JSONRPCErrorLike = Error | JSONRPCError;
````
both of which are wrong.

Also there seems to be no case where the callback gets passed three parameters as this type alleges:
```js
interface JSONRPCCallbackTypeSugared {  
    (err?: Error | null, error?: JSONRPCErrorLike, result?: JSONRPCResultLike): void
}
```

This is also the case for the promise-based type definitions.

The docs also suggest that the first parameter can be a JSON RPC response _or_ an `Error` object which doesn't seem to be the case anymore.

**Comment by ctusch** [comment]
@tedeh Sorry to nag but the first callback parameter is still `JSONRPCErrorLike` which is not what actually gets passed. Both parameter get passed a whole JSON RPC response object.

**Comment by tedeh** [comment]
I think I understand what you mean now.

Callback 'sugaring' is made only by requests made with `jayson.Client` and derived classes, so I believe we can leave that out of this.

**Comment by tedeh** [comment]
Can you have a look at 1955f3f and comment on that please.

**Comment by ctusch** [comment]
Looks exactly right to me!
