### ISSUE TITLE
Reason: TypeError: asn.define is not a function 

### ISSUE THREAD

**Issue by ArtyomBist** [tedeh/jayson#187]
Get Error after compile with vue/typescript/laravel mix - Reason: TypeError: asn.define is not a function 

`const jayson = require('jayson');
const rpcClient = new jayson.client.http({
  host: 'http://localhost.com/api/v2/',
  port: 80
});`

**Comment by addonn** [comment]
> Get Error after compile with vue/typescript/laravel mix - Reason: TypeError: asn.define is not a function
> 
> `const jayson = require('jayson'); const rpcClient = new jayson.client.http({ host: 'http://localhost.com/api/v2/', port: 80 });`

how it got resolved?
