### ISSUE TITLE
How to run testing against Jayson

### ISSUE THREAD

**Issue by Full-Stack-Shokhboz-Abdullayev** [tedeh/jayson#196]
Hello! 

I am wondering if Client.http() can be tested. For instance making, unit or e2e tests against Jayson seems to be not stated in the docs. I would really appreciate it if you gave me some examples to test my router (redirector) that is made with Jayson.Client.http(), and preferably if you used Jest as a testing library. 

Thanks in advance.

**Comment by tedeh** [comment]
You can find the existing test suite here: https://github.com/tedeh/jayson/blob/master/test/http.client-server.test.js
