### ISSUE TITLE
"undefined" params works while "null" params not

### ISSUE THREAD

**Issue by RetricSu** [tedeh/jayson#204]
we have a real-world [use case](https://github.com/nervosnetwork/godwoken-web3/issues/313) where users send such a request:

```sh
{
    "id": 1,
    "jsonrpc": "2.0",
    "method": "eth_blockNumber",
    "params": null
}
```

the request will result in an `invalid request` error while other JSON-RPC frameworks seem not.

however, the following with undefined params works:

```sh
{
    "id": 1,
    "jsonrpc": "2.0",
    "method": "eth_blockNumber"
}
```
because of this line of code https://github.com/tedeh/jayson/blob/master/lib/utils.js#L331

I do wonder since other frameworks tolerate the null params, can we allow that as well?

- https://github.com/tedeh/jayson/pull/205

**Comment by tedeh** [comment]
Setting params to `null` is unfortunately not valid JSON-RPC 2.0: https://www.jsonrpc.org/specification#parameter_structures
