### ISSUE TITLE
@type dependencies should be devDependencies

### ISSUE THREAD

**Issue by fboucquez** [tedeh/jayson#206]
Hi team, 

I'm wondering if there is any reason why typescript types are included as regular [dependencies](https://github.com/tedeh/jayson/blob/master/package.json#L52)...

Cheers
Fernando

**Comment by tedeh** [comment]
I don't know why it's like that. The Jayson typescript definitions depend on those external definitions. Would moving the external definitions to dev dependencies not mean trying to use the Jayson ts definition to fail on a clean install of Jayson?

**Comment by fboucquez** [comment]
Hi @tedeh , sorry for the later response. Should the types be moved to dev dependencies?

**Comment by fboucquez** [comment]
In general, you include a type dependency if you use the lib directly in a TS project. In our case we are javascript and even in typescript, you should avoid using transitive dependencies (only import and use jayson modules for example).
