### ISSUE TITLE
Request timing out after 5 seconds. 

### ISSUE THREAD

**Issue by brianluong** [tedeh/jayson#222]
I'm unsure why, but the `jayson` client is timing out after 5s. I tried connecting to different servers, all of which are configured with no timeouts, but the client still timed out after 5 seconds.

```
const jaysonCtor = jayson.Client.http;

const client = jaysonCtor({
  host: url.hostname,
  port: url.port,
  host: "localhost",
  port: 8080,
  path: "/",
});

const startTime = Date.now();
try {
  deployResult = await client.request("my_method");
} finally {
  const endTime = Date.now();

  log.info("Latency .", {
    durationMs: endTime - startTime,
  });
  }
```

Error is :
```
2023-10-09T21:47:42.196Z info: Latency . {"durationMs":5009}
2023-10-09T21:47:42.200Z error: Error running function. socket hang up
Error: socket hang up
    at connResetException (node:internal/errors:720:14)
    at Socket.socketCloseListener (node:_http_client:468:25)
    at Socket.emit (node:events:526:35)
    at Socket.emit (node:domain:489:12)
    at TCP.<anonymous> (node:net:337:12)
 {"code":"ECONNRESET","stack":"Error: socket hang up\n    at connResetException (node:internal/errors:720:14)\n    at Socket.socketCloseListener (node:_http_client:468:25)\n    at Socket.emit (node:events:526:35)\n    at Socket.emit (node:domain:489:12)\n    at TCP.<anonymous> (node:net:337:12)"}
```

1. Is this expected behavior? Or a bug?
2. Can we bump this default limit? 5s seems kind of low. I saw a code sample on adding timeouts, but the problem is I cannot touch this code since it's part of an externally owned library.

**Comment by tedeh** [comment]
All HTTP client options can be found here https://nodejs.org/api/http.html#httprequestoptions-callback including timeout

**Comment by bannier** [comment]
Isn't it because of this @brianluong?
https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V19.md#https11-keepalive-by-default
> HTTP(S)/1.1 KeepAlive by default
Starting with this release, Node.js sets keepAlive to true by default. This means that any outgoing HTTP(s) connection will automatically use HTTP 1.1 Keep-Alive. **The default waiting window is 5 SECONDS**. Enable keep-alive will deliver better throughput as connections are reused by default.
