### ISSUE TITLE
Feature Request: Adapt to more environments

### ISSUE THREAD

**Issue by axetroy** [tedeh/jayson#233]
Due to the JSON-RPC specification, which only defines how to handle JSON requests, it does not specify where the JSON data comes from.

Therefore, theoretically, JSON-RPC can be used in any environment, as long as your data is in JSON format.

For example, if I want to start a JSON-RPC service in a Web Worker, I can do it like this:

1. Add Web Worker support in the source code
2. Start the RPC service

```js
const jayson = require('jayson');

// create a server
const server = new jayson.Server({
  add: function(args, callback) {
    callback(null, args[0] + args[1]);
  }
});

server.webWorker().listen();
```

3. Call from the main thread

```js
const worker = new Worker('worker.js');

const client = jayson.client.worker(worker);

client.request('add', [1, 1], function(err, response) {
  if(err) throw err;
  console.log(response.result); // 2
});
```

This series of steps allows JSON-RPC to be used within a Web Worker.

But this approach is too limited, so is there a more general way to achieve this?

I hope Jayson can expose some APIs to allow users to adapt these environments themselves.

**Comment by tedeh** [comment]
Jayson exposes everything you need to work with JSON-RPC requests outside of the included transports, and the issue you are raising is already discussed extensively in the documentation: https://github.com/tedeh/jayson?tab=readme-ov-file#what-is-the-recommended-way-to-use-jayson
