### ISSUE TITLE
Passing a request without params can cause the server to crash.

### ISSUE THREAD

**Issue by nackjicholson** [tedeh/jayson#40]
Let's say this is my rpc server.

```
var jayson = require('jayson');

var server = jayson.server({
  add: function(a, b, callback) {
    callback(null, a + b);
  }
});

server.http().listen(3000);
```

If I were to have a client post this:

```
{"jsonrpc":"2.0","method":"add","params":[1, 2]}
```

That would work correctly and I would get back `3`.

But if I make a simple mistake like this:

```
{"jsonrpc":"2.0","method":"add","params":[]}
```

This will always throw a fatal error and crash the server.

What I would expect to be correct behavior is that `a` and `b` should become set to `undefined` because they weren't passed as params. That would be okay... worst case scenario you get a nonsensical response back like `null` because that's the result of `undefined + undefined`. But what actually happens is: `b` and `callback` become `undefined` and `a` becomes the callback function.

So when the `callback` is called you get a Fatal error message telling you `undefined` is not a function, and the server crashes.

There is an absolutely ridiculous way to get around it, and at least keep the server running.

```
var jayson = require('jayson');

var server = jayson.server({
    add: function(a, b, callback) {
      if (typeof a === 'function') {
        callback = a;
        a = undefined;
      }

      if (typeof b === 'function') {
        callback = b;
        b = undefined;
      }

      callback(null, a+b);
    }
});

server.http().listen(3000);
```

I've looked through your module a little bit. I've also looked at other json-rpc modules on npm and I have to say, code clarity wise yours is by far the best. So :+1: to you!

I would like to make a fork and do a pull request to address this issue. Do you see this as an actual issue? Or is this the intended behavior. As long as I'm running my server as a daemon which restarts when it fails, I'm not really too concerned about it. But yeah I kind of see it as a bad thing to have a simple typo or mistake in the request payload cause a server crash.

**Comment by tedeh** [comment]
Thanks for the heads up, I will take a look at it this weekend.

**Comment by tedeh** [comment]
I think this behavior will stay for jayson to continue to be backwards-compatible, however, I am working on a new way to define methods which will provide better handling of things such as parameters. I suppose you will have to wait for that.

Look into the [usage of domains](https://nodejs.org/api/domain.html) if you want to prevent your server from crashing.
