### ISSUE TITLE
Handling wrong number of arguments

### ISSUE THREAD

**Issue by bdunlay** [tedeh/jayson#44]
The server chokes when it doesn't get the right number of arguments. For example, say you have a very simple server that defines an `add` method:

```
var jayson = require("jayson");

var server = jayson.server({
  add: function(a, b, callback) {
    callback(null, a + b);
  },
});

server.http().listen(3000);
```

Using the CLI we can send it a request with the wrong number of parameters:

```
jayson -u http://localhost:3000 -m add -p [1]
```

Th result is that the server throws an unhandled exception, and then eventually the client dies because of a closed TCP connection. 

```
$ jayson -u http://localhost:3000 -m add -p [1]
-> add(1)
<- Error: socket hang up
    at createHangUpError (http.js:1472:15)
    at Socket.socketOnEnd [as onend] (http.js:1568:23)
    at Socket.g (events.js:180:16)
    at Socket.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```

```
$ node simpleserver.js 
.../simpleserver.js:6
    callback(null, a + b);
    ^
TypeError: undefined is not a function
    at jayson.server.add (.../simpleserver.js:6:5)
    at Method.execute (.../node_modules/jayson/lib/method.js:124:20)
    at .../node_modules/jayson/lib/server.js:284:12
    at maybeParse (.../node_modules/jayson/lib/server.js:401:5)
    at Server.call (.../node_modules/jayson/lib/server.js:229:3)
    at .../node_modules/jayson/lib/utils.js:180:14
    at .../node_modules/jayson/node_modules/lodash/index.js:7173:25
    at .../node_modules/jayson/lib/utils.js:153:7
    at Object.Utils.JSON.parse (.../node_modules/jayson/lib/utils.js:273:3)
    at IncomingMessage.<anonymous> (.../node_modules/jayson/lib/utils.js:151:16)
```

Shouldn't it handle this and return an error to the client?

**Comment by bdunlay** [comment]
This should return "invalid args" per [this thread](https://groups.google.com/d/msg/json-rpc/NtrtB-Lb1Sw/_6uxB1pi-CMJ) on the json-rpc discussion group.

**Comment by tedeh** [comment]
With the new method definition in 1.2, I would consider this issue resolved. I recommend something like this:

```javascript
var jayson = require('jayson');
var _ = require('lodash');

var methods = {
  add: function(args, done) {
    // deals with any type of "args" as long as it is iterable
    var sum = _.reduce(args, function(sum, val) { return sum + val; }, 0);
    done(null, sum);
  }
};

var server = jayson.Server(methods, {
  collect: true // the important change
}); 
```

Your client may call add with either an Array or an Object as params. If you want to have a method that returns an error when something is wrong with the params you can return it yourself by passing the result of `this.error(jayson.Server.errors.INVALID_PARAMS)` to `done`.

**Comment by jonseymour** [comment]
One comment on this change.

Our library github.com/ninjablocks/usvc uses jayson 1.1.1 to implement a JSON RPC server. Our server method handlers are wrapped by some middleware handlers which use the JS arguments object to process the passed arguments. The validation performed with this change now causes our requests to fail (I think) because the wrapper functions presented to the Jayson API do not have the expected number of formal parameters.
