### ISSUE TITLE
Documentation class names inconsistancy

### ISSUE THREAD

**Issue by bdunlay** [tedeh/jayson#48]
I've noticed an inconsistency between classes name and the documentation for the respective classes:

|Class Name   |Documented As|
|-------------|-------------|
|`HttpClient` |ClientHttp |
|`HttpServer` |ServerHttp |
|`HttpsClient`|ClientHttps|
|`HttpsServer`|ServerHttps|
|`TcpServer`  |ServerTcp  | 

Example: [`TcpServer`](https://github.com/tedeh/jayson/blob/master/lib/server/tcp.js#L6) & [ServerTcp](https://github.com/tedeh/jayson/blob/master/lib/server/tcp.js#L13)

`TcpClient` does not follow this convention:

|Class Name   |Documented As|
|-------------|-------------|
|`TcpClient`  |TcpClient  | 

I think they should all be like the `TcpClient` (documentation name matching class name) but would like to run it by you before you take my tls-support PR so I can follow the proper documentation naming convention.

**Comment by tedeh** [comment]
I prefer the "Documented as" version and will probably change the other class names eventually. This means the TcpClient should be ClientTcp.

**Comment by bdunlay** [comment]
resolved with #47
