### ISSUE TITLE
Circular references

### ISSUE THREAD

**Issue by gillesdemey** [tedeh/jayson#66]
A simple circular reference will respond with an error, refering to https://github.com/tedeh/jayson/blob/master/lib/utils.js#L295-L299

Could we leverage something like https://github.com/isaacs/json-stringify-safe to send a valid JSON response regardless of circular references in the response?

**Comment by tedeh** [comment]
Good idea, do you want to make a PR?

**Comment by gillesdemey** [comment]
Sure, I'll even throw in a test for you! ;)
