### ISSUE TITLE
Specify charset in Content-Type

### ISSUE THREAD

**Issue by francisdb** [tedeh/jayson#68]
The jayson server returns `Content-Type` header `application/json` with `utf-8` body
Some http clients default to `ISO_8859_1` as default charset which cause issues

The specs seem to be a bit unclear on this:
http://stackoverflow.com/questions/2325571/for-http-responses-with-content-types-suggesting-character-data-which-charset-s

As far as I know the JSON-RPC spec has no specific charset defined.

In any case I think it would not be bad to explicitly set `Content-Type` to `application/json; charset=utf-8` (or the encoding defined in the options)

**Comment by francisdb** [comment]
@tedeh the current fix will cause problems in case `options.encoding` is not `utf8`. (mind the difference in )

**Comment by tedeh** [comment]
I agree, will look into this the coming days.

**Comment by francisdb** [comment]
Thanks @tedeh

**Comment by tedeh** [comment]
I have been thinking and I belive that it is best that you implement your own middleware that calls a `jayson` server if you want to do funky stuff with encodings. The [node.js option](https://nodejs.org/api/all.html#all_buffers_and_character_encodings) `encoding` is not directly translatable to the charset value of the header `content-type` and you would need to use a package like [iconv-lite](https://github.com/ashtuchkin/iconv-lite) if you want to send back `ISO-8859-1` or similar.

I would do something like this (not tested):

```javascript
var jayson = require('jayson');
var connect = require('connect');
var iconv = require('iconv-lite');

var server = jayson.Server(/* ... */);
var app = connect.createServer();

app.use(connect.json()); // or whatever the "parse-body-as-JSON" middleware is called
app.use(function(req, res, next) {
  server.call(req.body, function(error, success) {
     var charset = 'iso-8859-1';
     var response = JSON.stringify(error || success);
    
     res.setHeader('Content-Type', 'application/json; charset=' + charset);
     res.end(iconv.encode(response, charset));
  });
});
```

`iconv.encode` returns a buffer which means that you don't have to set the encoding.

**Comment by francisdb** [comment]
I can live with this, as long as the default utf-8 us set up correctly.
