### ISSUE TITLE
[Question] Can the transport server be the RPC client?

### ISSUE THREAD

**Issue by nathanhourt** [tedeh/jayson#73]
Hi there. I need a JSON-RPC connection where the TCP server is the RPC client and vice versa. Basically, this means I want to create a JSON-RPC server around a [WebSocket object](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket) in the browser. Can I do this with jayson or any other JSON-RPC library you know of? Right now the only way I'm finding to do this would be to manually invoke the middleware function, but I'm not sure how to prepare the request and response objects to do that, and there's no point figuring out how to make that work if there's an easier way.

Thanks. :)

**Comment by tedeh** [comment]
If I understand you correctly, I believe you should use a solution like [socket.io](https://github.com/socketio/socket.io) that has support for RPC-style messages.
