### ISSUE TITLE
es6 class as handler

### ISSUE THREAD

**Issue by ghanto** [tedeh/jayson#74]
Hey,

I tried to pass es6 class instead of function - I've got 
`TypeError: Class constructor GetMethod cannot be invoked without 'new'`

It happened because `Method.prototype.execute` expects that a handler is a function (it just calls it and replaces a context). I've checked why it does not work properly for my code and I found this:
https://github.com/tedeh/jayson/blob/master/lib/method.js#L120

First problem for me is that it overrides my context - if I use for handling  a class which inherits prototype from any abstract class, it also overrides this prototype.

For example, I have the handler defined this way:

``` javascript
var AbstractMethod = function () {
    this.randomprop = 'kex';
}
```

``` javascript
var AbstractMethod = require('./AbstractMethod.js');

var GetMethod = function (args, callback) {
    AbstractMethod.call(this);
    console.log('GetMethod', this);
    // prints "GetMethod { jayson server props }"
    this.test(callback);
    //TypeError: this.test is not a function (because prototype was replaced by 'call' in #120)
};

GetMethod.prototype = Object.create(AbstractMethod.prototype);

GetMethod.prototype.test = function (callback) {
    console.log('test/callback')
    callback(null, 'ok')
}
```

Changing `lib/method.js#120` from
`return handler.call(server, params, callback);`
to
`return new handler(server, params, callback);`

solves my problem, but it's not good solution for people who currently use it. `server` object is available in the constructor (I can use it if I want and drop if I don't need it), my `this` context is not affected and it creates an instance  when class is defined with `class` operator.

What do you think about new options (for es6 support with backward compatibility), for example:
- `es6_classes_support` - enables possbility to pass es6 class as handler
- `rewrite_context` - rewrites context of handler (`true` as default, because it currently works this way) 

Of course, I can make a PR, but I want to know what do you think about it. It's ~20 lines of code.

Best Regards

**Comment by tedeh** [comment]
I'll consider not forcing the `this` value of a method, probably using an option in the server called `methodScope`, `scope` or something like that.

In the meantime, you can subclass `jayson.Method` and override `jayson.Method.prototype.execute` with something that works better. The method is very short so you are unlikely to mess something up. You might also find the server option `methodConstructor` to be convenient.

**Comment by ghanto** [comment]
Ok, I've prepared subclass that inherits from `jayson.Method`, I pass it to the `methodConstructor ` option and it works as I want. I'll make a PR but tell me: you'll provide official solution soon and my code will be removed? (I mean `scope`/`methodScope` that you wrote about)

I'm asking because I don't know if I should update documentation and tests also.

**Comment by tedeh** [comment]
I will consider how to solve this in the best way for a while, then prepare an update.

**Comment by crabicode** [comment]
@tedeh, any updates?

**Comment by tedeh** [comment]
Forgot about this, but an immediate fix would be to just bind the method before, like this (not tested):

```javascript
const jayson = require('jayson');

const AbstractClass = function() {
  // this is the important part
  this.getMethod = this.getMethod.bind(this);
}

AbstractClass.prototype.getMethod = function() {
  return function(args, done) {
    done(null, args);
  };
};

const concreteClass = new AbstractClass();

const method = new jayson.Method(concreteClass.getMethod());
const server = new jayson.server({
  reflect: method
});
```

The problem is essentially a JavaScript classic: passing around unbound functions, and is the whole reason utility functions such as `lodash` and `underscore` [_.bindAll](https://lodash.com/docs/4.17.4#bindAll) exist.
