### ISSUE TITLE
Test for a "thenable" instead of `promise instanceof Promise`

### ISSUE THREAD

**Issue by vjpr** [tedeh/jayson#75]
In `PromiseMethod` the test is: `wasPromised = promise instanceof Promise;`.

This does not work when using `babel` and ES7 `async` promises.

Instead we should just test for `if ("then" in promise)`...

**Comment by tedeh** [comment]
I _promise_ to look into it

**Comment by tedeh** [comment]
Released in `2.0.2`.

**Comment by vjpr** [comment]
Thanks for *resolving* 😉
