### ISSUE TITLE
Use Jayson as handler function in http server code

### ISSUE THREAD

**Issue by jpike88** [tedeh/jayson#76]
Check out this [link](https://github.com/andris9/node-jsonrpc)

I'm able to use a handler inside a createServer function, which means that non-POST requests can be 
handled cleanly along file serving handlers like [Lactate](https://github.com/snowblindroan/-Unmaintained-Node-file-server) (look at the section titled 'Creating a directory handler')

Is there any way of doing the same with this library?

**Comment by tedeh** [comment]
Use the middleware.

**Comment by jpike88** [comment]
I read the documentation, but it's not clear how I would go about it. If it's something Jayson is capable of being used for, it's not immediately clear to me.

What would the code look like, injecting the handler into a createServer function and isolating POST requests?

**Comment by tedeh** [comment]
I suggest that you look at the examples, and read up on how to use [connect](https://github.com/senchalabs/connect).
