### ISSUE TITLE
Ability to pass debug information in a response

### ISSUE THREAD

**Issue by vjpr** [tedeh/jayson#77]
I want to be able to access debug information about a response. Currently whatever I return from the handler must be what will be the reply. To work around it I must make my results into objects and attach an `info` property, and then in the `server.call` callback I must filter this from being sent.

```
server.call(message, (error, success, info) => {

}
``` 

Maybe adding an info field to the callback as above would resolve this?

I think the more generic concept to enable this functionality would be to allow middleware in the request/response flow like Express/Koa.

**Comment by tedeh** [comment]
I don't understand what you want to do. Jayson won't be getting middleware, this has been discussed previously. If you want to affect how you write handlers, subclass `jayson.Method` and create your own rules.
