### ISSUE TITLE
Unable to use https with SSL certs

### ISSUE THREAD

**Issue by jpike88** [tedeh/jayson#80]
```
var credentials = {
    key: fs.readFileSync('./certs/key.pem'),
    cert: fs.readFileSync('./certs/cert.crt'),
    ca: fs.readFileSync('./certs/intermediate.crt')
};

server.https(credentials).listen(8000);
```

That doesn't work. Please update your documentation to describe the proper way to support HTTPS

**Comment by tedeh** [comment]
Well, [the tests](https://github.com/tedeh/jayson/blob/master/test/https.client-server.test.js) work and the [node js documentation](https://nodejs.org/api/https.html#https_https_createserver_options_requestlistener) confirms the usage so I think you must be doing something wrong.
