### ISSUE TITLE
exception callback

### ISSUE THREAD

**Issue by ctusch** [tedeh/jayson#82]
Hey!

I'm using the promise-based interface and I'm having some troubles logging exceptions my methods throw. Currently I have to .then my own promise in every method in order to log a potential exception. What do you think of a callback property on the server object that gets called whenever a method "throws" an exception?

**Comment by tedeh** [comment]
Hello,

The response is emitted as an event for every call, errors included.

See https://github.com/tedeh/jayson#server-events

Rejections are handled by jayson `then`-ing the actual promise returned by the method, which you can see here:

https://github.com/tedeh/jayson/blob/master/promise/lib/method.js#L38

I did not get a chance to try, but I think even exceptional errors should be emitted by the server as per the "Server Events" section in the README.

**Comment by ctusch** [comment]
Hey,

thanks for the links! I must have missed the server events chapter. I've tried it now but it also just returns the JSON RPC error (which makes sense, since that's what the response is).

It looks like this:
`{
    jsonrpc: '2.0',
    id: '731480f8-9876-48c7-85e1-a3e1bfe7e987',
    error: { code: -32603, message: 'Internal error' }
} 
`

So I don't have the opportunity to log the actual exception in this event listener either.

Do you have any other ideas?

**Comment by tedeh** [comment]
I think it is best for you to override/subclass the `jayson.PromiseMethod` and specifically the `execute` method. That way you get complete control over what is returned from methods.

See https://github.com/tedeh/jayson/blob/master/promise/lib/method.js#L28

**Comment by ctusch** [comment]
That should work, thanks!

**Comment by ctusch** [comment]
Sorry for the late response but how would I go about overriding the implicit use of `jayson.PromiseMethod`? You ignore the `methodConstructor` option passed to the `jayson.PromiseServer`: https://github.com/tedeh/jayson/blob/5965aef406954497e195a46faddb45a21df55ed1/promise/lib/server.js#L16

Is there any other way without having to wrap every single method definition explicitly?

**Comment by tedeh** [comment]
I adressed this in the latest commit bc99be626eaf45adb31a1c0f660da1d5bcc2490e

**Comment by ctusch** [comment]
Thank you for your support! :)

**Comment by ctusch** [comment]
@tedeh Sorry to bother you again... but I'm still not able to access the exception thrown. It's because you swallow it here:
https://github.com/tedeh/jayson/blob/master/promise/lib/method.js#L40

Could you change that to return the original promise like this:
```JavaScript
    promise.then(
      function(fulfilled) { outerCallback(null, fulfilled); },
      function(rejected) { outerCallback(rejected); }
    );
    return promise;
```
