### ISSUE TITLE
32600 - Invalid request

### ISSUE THREAD

**Issue by LeaklessGfy** [tedeh/jayson#83]
Hello,

First, thanks for your wonderfull work.

I'm trying to have a both communication point from Golang (client - serv) and Node (with your lib) (client serv)

When I try from my program in Go to call 127.0.0.1 3000 (because I'm running the node server on local). I got the following message :+1: 
```
[{"jsonrpc":"2.0","id":null,"error":{"code":-32600,"message":"Invalid request"}},{"jsonrpc":"2.0","id":null,"error":{"code":-32600,"message":"Invalid request"}}]
```

Have you any doc that could allow me to bind a valid request because for now I just send to the server (in json) an array of int like =>
```
[10, 10]
```

The server code =>
```
// create a server
var server = jayson.server({
  add: function(args, callback) {
    callback(null, args[0] + args[1]);
  }
});

server.tcp().listen(3000);
```

Client code in go => 
```
var reply int
conn, err := net.Dial("tcp", r.Client[0].Addr)

if err != nil {
	fmt.Println(err)
	return
}

defer conn.Close()

c := jsonrpc.NewClient(conn)
err = c.Call("add", []int{10, 10}, &reply)

if err != nil {
	fmt.Println(err)
	return
}
	
fmt.Printf("Add: %d", reply)
```

Thank you :)

**Comment by LeaklessGfy** [comment]
I found out what should I specify in my request like =
```
{"jsonrpc":"2.0", "method":"add", "params":[10,10]}
```

But now I got an other problem. (I try using telnet). When I send this with telnet I can't have an answer from the server (basically 10 + 10 result in this example). But callback seem to be a valid function when I console.log it...

**Comment by LeaklessGfy** [comment]
Okay really sorry @tedeh I'm starting to understand.

On the server/index.js we got those line =>
```
 var respond = function(error, result) {
      if(utils.Request.isNotification(request)) return callback();
      var response = utils.response(error, result, request.id, self.options.version);
      if(response.error) callback(response);
      else callback(null, response);
    };
```

It seems that when I call the server with the former parameter I mention, the first if is activate =>
```
 if(utils.Request.isNotification(request)) return callback();
```

Because callback() has no argument it's an undefined response sent. If I comment this line. Everything seems fine and I got the excepted answer : 
```
{"jsonrpc":"2.0","id":null,"result":20}
```

**Comment by LeaklessGfy** [comment]
Ok I understand it by looking at utils.isNotification, I need an "id" to get the answer.
Thanks !

**Comment by tedeh** [comment]
He he, yes, you need an ID or your request is considered a notification, which means that it does not expect a response.
