### ISSUE TITLE
api endpoint

### ISSUE THREAD

**Issue by WarL0ckNet** [tedeh/jayson#85]
How set path endpoint if use jayson as middleware?
`let Api = require('../api/'),
	api = new Api(),
	jayson = require('jayson');
var server = jayson.server(api.getMethods());
module.exports = function(app) {
	app.use(server.middleware());
};`
How make API endpoint for example: http://example.com/api ?

**Comment by tedeh** [comment]
Use [express](https://github.com/expressjs/express).

**Comment by WarL0ckNet** [comment]
Cool :) I am understand this. I show part my code where define routing.
Ok, from you example:
`// parse request body before the jayson middleware
app.use(jsonParser());
app.use(server.middleware());`
Where endpoint? In path  http://example.com/ endpoint '/'
In my code before app.use(server.middleware()); - app.route('/').get(callback1).post(callback2);
How define jayson to endpoint '/api'? Use **router** in options? Write example please.

**Comment by adriennn** [comment]
to listen to anything coming or going to/from `/api` endpoint and handle various methods

```javascript
var methods= {
   function1: function(args, callback) {
      callback(null, args[0 ... ])
   },
   function2: function(args, callback) {
      callback(null, args[0] ...)
   }
}

app.use('/api', jayson.server(methods).middleware());
```
