### ISSUE TITLE
Unix Socket Support?

### ISSUE THREAD

**Issue by mrb1090** [tedeh/jayson#90]
Curious if this supports Unix Sockets.  Looking for a JSON-RPC implementation to use in a Node Cluster environment...

Thx,

Mike B.

**Comment by tedeh** [comment]
Yes, it does. README [on the client](https://github.com/tedeh/jayson#clienttcp) updated to confirm this.

**Comment by mrb1090** [comment]
Thanks!

**Comment by tedeh** [comment]
Use the `path` option that is described here:

https://nodejs.org/api/net.html#net_socket_connect_path_connectlistener

````javascript
var client = jayson.client.tcp({path: pathToIPCSocket});
````

**Comment by DrSensor** [comment]
Hello,

Is it possible to receive and send RPC method at the same socket?
I have some use case to have 2 way RPC in 1 node app (client & server at the same time) in 1 socket.

> In C# there is [library](https://github.com/Microsoft/vs-streamjsonrpc/blob/master/doc/index.md#receiving-remote-notifications-and-requests) that have this funtionality

Thanks,
Wildan
