### ISSUE TITLE
RPC call over TCP is expensive!!

### ISSUE THREAD

**Issue by atton16** [tedeh/jayson#92]
I did a packet analysis and found that RPC call over TCP is too expensive. It cost **12** packets to perform each call when in fact it could simply leverage TCP keep-alive. RPC call should be less expensive than REST API call. Please fix this. Cheers.

**Comment by tedeh** [comment]
I don't have the time to look into this right now, but a more efficient implementation should be possible and you are most welcome to provide a hopefully backwards-compatible pull request with your ideas/requirements.

**Comment by gzz2000** [comment]
Bumping this issue as I find that sometimes keepalive is a requirement when the RPC server keeps session information associated with each TCP connection. In that way, it no longer works if each time we have to start a new connection.

**Comment by tedeh** [comment]
This issue has been referenced from an important section in the README: https://github.com/tedeh/jayson#what-is-the-recommended-way-to-use-jayson

**Comment by gzz2000** [comment]
> This issue has been referenced from an important section in the README: https://github.com/tedeh/jayson#what-is-the-recommended-way-to-use-jayson

You are right. Then this is purely a consideration on efficiency. Submitted a PR implementing this.
