### ISSUE TITLE
Jayson module incompatible with Node.js application packager (pkg)

### ISSUE THREAD

**Issue by gschmottlach-xse** [tedeh/jayson#93]
I am using [pkg](https://www.npmjs.com/package/pkg) to package my Node.js module into a single file executable. Your module (jayson) is great but unfortunately, due to the way you've specified your module exports in the following files:

jayson/index.js
jayson/promise/index.js

the *pkg* program cannot follow your dependencies. Specifically, the contents of *jayson/index.js* looks like this:
`
module.exports = require(__dirname + '/lib');
`
It (*pkg*) cannot automatically concatenate the strings together. I'm wondering if just relative paths might solve this issue, e.g.
`
module.exports = require('./lib');
`

Is there any reason you used a fully qualified path? In order to work around this, I have to explicitly reference these files for *pkg* by including these dependencies in my package.json file for my module:

### Package.json *PKG* configuration object
`
"pkg": {
    "scripts": [ 
              "node_modules/jayson/lib/**/*.js",
              "node_modules/jayson/promise/**/*.js"
    ]
  },
`

This tells *pkg* to include these JavaScript files in the snapshot file-system it creates. Is this anything you could investigate? Short of forking your repo and making changes, I don't see another alternative.

Thanks for your consideration . . .

**Comment by tedeh** [comment]
Hey,

There is no good reason for the absolute directory requires so I've fixed this in 2.0.4. Thanks for highlighting this issue.
