### ISSUE TITLE
Error handling in client callback

### ISSUE THREAD

**Issue by fccxor** [tedeh/jayson#95]
Example:

var server = jayson.server({
  add: function(args, cb) {
var error = this.error(-32602);
cb(error);
  }
});

On the client side, the callback(err, response) {});
although response contains the proper JSONRPC object for error (response.error), err returns null.
so if(err) will always return 0.

**Comment by tedeh** [comment]
Explicitly documented in the README:

https://github.com/tedeh/jayson#client-callback-syntactic-sugar

**Comment by MrSkinny** [comment]
@tedeh In what circumstance would the client actually receive an `err` in its first param since the server's valid error object only ever ends up inside the `response.error`?

**Comment by tedeh** [comment]
Network errors typically.
