### ISSUE TITLE
utils.getParameterNames regex issue

### ISSUE THREAD

**Issue by sssession** [tedeh/jayson#98]
first I add a method as below.

```javascript
jayson.server({
    a() {
        console.log(arguments);
    }
}, {collect: false})
```

The `utils.getParameterNames` will parse the params as  `[ ') {                     console.log(arguments' ]`.

And the request result is 
```json
{
    "jsonrpc": "2.0",
    "id": "1212312",
    "error": {
        "code": -32602,
        "message": "Invalid method parameter(s)"
    }
}
```

expected the result is `[]`

**Comment by tedeh** [comment]
I don't advise on relying on argument parsing. With ES6, doing this has become non-sensical anyway.

Try parsing this function into something workable with jayson: `function([a, b], {c: {d:e = 5}) { /* [...] */ }`.

I've decided to remove argument parsing in jayson 3, but will fix this particular bug for you.

**Comment by tedeh** [comment]
After looking more carefully, I've noticed that this is not a bug. You need to give a callback as a parameter.  Jayson parses the arguments just fine.
